name: Build and upload Docker image to AWS ECR

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure credentials for AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::936892409162:role/github-actions-BKmetoff-endurosat-assignment
          aws-region: eu-west-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: endurosat-assignment
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo '=== Building image ==='
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          echo '=== Pushing image to $REGISTRY/$REPOSITORY:$IMAGE_TAG ==='
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo '=== Image pushed ==='
