name: Build and upload Docker image to AWS ECR

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure credentials for AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::936892409162:role/github-actions-BKmetoff-endurosat-assignment
          aws-region: eu-west-1

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: endurosat-assignment
          IMAGE_TAG: latest
        run: |
          echo '\n\n=== Building image ===\n\n'
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          echo '\n\n=== Pushing image ===\n\n'
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          echo '\n\n=== Image pushed ==='
