name: CI pipeline for Production

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  build_image_and_push_to_production:
    uses: ./.github/workflows/build_and_push_production.yaml
    permissions:
      id-token: write
      contents: read

  update_production_ecs_cluster:
    needs: build_image_and_push_to_production
    if: ${{ success() }}
    uses: ./.github/workflows/update-ecs-cluster.yaml
    secrets:
      ENVIRONMENT: production
      REGION: eu-west-1
    permissions:
      id-token: write
      contents: read
