name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  run_tests_and_linter:
    uses: ./.github/workflows/runs-tests-and-linter.yaml

  build_and_push_image:
    needs: run_tests_and_linter
    if: ${{ success() }}
    uses: ./.github/workflows/build-and-push-dk-image.yaml
