name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  run_tests_and_linter:
    uses: ./.github/workflows/runs-tests-and-linter.yaml

  build_image_and_push_to_staging:
    needs: run_tests_and_linter
    if: ${{ success() }}
    uses: ./.github/workflows/build_image_and_push_to_staging.yaml
    permissions:
      id-token: write
      contents: read
